export const ADD_INGRIDIENT = 'ADD_INGRIDIENTS';
export const REMOVE_INGRIDIENT = 'REMOVE_INGRIDIENTS';
export const SET_INGRIDIENT = 'SET_INGRIDIENT';
export const FETCH_INGRIDENTS_FAILED = 'FETCH_INGRIDENTS_FAILED';

export const BURGER_PURCHASE_SUCCESS = 'BURGER_PURCHASE_SUCCESS';
export const BURGER_PURCHASE_FAILED = 'BURGER_PURCHASE_FAILED';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const INIT_PURCHASE = 'INIT_PURCHASE';
export const FETCH_ORDER_INIT = 'FETCH_ORDER_INIT';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED';

